openapi: 3.0.5
info:
  version: 0.0.1
  title: hpcutils

paths:
  /health_check:
    get:
      tags:
        - health_check
      operationId: hpcutils.api.views.health_check
      summary: Check API alive
      responses:
        200:
          description: 'Checks to see if API is alive'

  /delete/{cluster}/{project_name}/job:
    delete:
      tags:
        - delete
      operationId: hpcutils.api.views.delete_job
      parameters:
        - $ref: '#/components/parameters/JobId'
        - $ref: '#/components/parameters/Cluster'
        - $ref: '#/components/parameters/ProjectName'
      responses:
        200:
          description: 'successfully got project data'

  /get/{cluster}/{project_name}/logs:
    get:
      tags:
        - logs
      operationId: hpcutils.api.views.get_logs
      parameters:
        - $ref: '#/components/parameters/JobId'
        - $ref: '#/components/parameters/Cluster'
        - $ref: '#/components/parameters/ProjectName'
        - $ref: '#/components/parameters/LogType'
      responses:
        200:
          description: 'successfully got logs'

  /get/{cluster}/{project_name}/metadata:
    get:
      tags:
        - metadata
      operationId: hpcutils.api.views.get_resource_metadata
      parameters:
        - $ref: '#/components/parameters/JobId'
        - $ref: '#/components/parameters/Cluster'
        - $ref: '#/components/parameters/ProjectName'
      responses:
        200:
          description: 'successfully got project data'

  /get/{cluster}/{project_name}/all:
    get:
      tags:
        - metadata
      operationId: hpcutils.api.views.get_project_jobs
      parameters:
        - $ref: '#/components/parameters/Cluster'
        - $ref: '#/components/parameters/ProjectName'
      responses:
        200:
          description: 'successfully got all jobs'

      # TODO add feature for sleecting A100, V100 gpus

  /create/{cluster}/{project_name}:
    post:
      tags:
        - create
      operationId: hpcutils.api.views.create_cluster_config
      parameters:
        - $ref: '#/components/parameters/Cluster'
        - $ref: '#/components/parameters/ProjectName'
        - $ref: '#/components/parameters/GithubUsername'
        - $ref: '#/components/parameters/GithubRepository'
      responses:
        200:
          description: 'successfully created cluster config'

        #- $ref: '#/components/parameters/Walltime'

        #- $ref: '#/components/parameters/StorageMem'

        # TODO update the get methods to enable basic filtering of results
  /create/{cluster}/{project_name}/venv:
    post:
      tags:
        - create
      operationId: hpcutils.api.views.create_venv
      parameters:
        - $ref: '#/components/parameters/Cluster'
        - $ref: '#/components/parameters/ProjectName'
      responses:
        200:
          description: 'successfully created venv'

  /delete/{cluster}/{project_name}/venv:
    delete:
      tags:
        - delete
      operationId: hpcutils.api.views.delete_venv
      parameters:
        - $ref: '#/components/parameters/Cluster'
        - $ref: '#/components/parameters/ProjectName'
      responses:
        200:
          description: 'successfully deleted venv'

  /run/gpu/{cluster}/{project_name}:
    post:
      tags:
        - run
      operationId: hpcutils.api.views.run_gpu_job
      parameters:
        - $ref: '#/components/parameters/Cluster'
        - $ref: '#/components/parameters/ProjectName'
        - $ref: '#/components/parameters/JobName'
        - $ref: '#/components/parameters/ScriptTemplateName'
        - $ref: '#/components/parameters/EnvVars'

      requestBody:
        $ref: '#/components/requestBodies/JobVars'
      summary: Submit myriad job
      responses:
        200:
          description: 'successfully submitted job'


components:
  parameters:
    LogType:
      name: log_type
      in: query
      required: true
      description: type of log to get
      schema:
        $ref: '#/components/schemas/LogType'
    JobId:
      name: job_id
      in: query
      required: false
      description: id of job
      schema:
        $ref: '#/components/schemas/JobId'
    JobName:
      name: job_name
      in: query
      required: true
      description: name of job
      schema:
        $ref: '#/components/schemas/JobName'
    GithubUsername:
      name: github_username
      in: query
      required: true
      description: github username
      schema:
        $ref: '#/components/schemas/GithubUsername'
    GithubRepository:
      name: github_repository
      in: query
      required: true
      description: github repository
      schema:
        $ref: '#/components/schemas/GithubRepository'
    ProjectName:
      name: project_name
      in: path
      required: true
      description: name of project
      schema:
        $ref: '#/components/schemas/ProjectName'
    Cluster:
      name: cluster
      in: path
      required: true
      description: name of cluster
      schema:
        $ref: '#/components/schemas/Cluster'
    Walltime:
      name: walltime
      in: query
      required: true
      description: maximum walltime to use
      schema:
        $ref: '#/components/schemas/Walltime'
    StorageMem:
      name: storage_mem
      in: query
      required: true
      description: temporary storage memory (in Gigs)
      schema:
        $ref: '#/components/schemas/StorageMem'

    EnvVars:
      name: environment_variables
      in: query
      required: true
      description: environment variables go here
      schema:
        $ref: '#/components/schemas/EnvVars'

    ScriptTemplateName:
      name: script_template_name
      in: query
      required: true
      description: path to bash script template
      schema:
        $ref: '#/components/schemas/ScriptTemplateName'

  requestBodies:
    JobVars:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JobVars'
  schemas:
    LogType:
      type: string
      enum: ["output", "error"]
    JobId:
      type: string
      default: ""
    GithubUsername:
      type: string
      example: namiyousef
    GithubRepository:
      type: string
      example: divergent-examples
    JobVars:
      type: object
      properties:
        walltime:
          $ref: '#/components/schemas/Walltime'
        storage_mem:
          $ref: '#/components/schemas/StorageMem'




    Cluster:
      type: string
      enum: ["myriad", "beaker"]
    ProjectName:
      type: string

    Walltime:
      type: string
      example: "6:00:00"
    StorageMem:
      type: integer
      example: 15
    JobName:
      type: string
    EnvVars:
      type: object
      example: {"env_vars": {"EPOCHS": 5, "BATCH_SIZE": 64, "MODEL_NAME": "xlm-roberta-base", "MAX_LENGTH": 128, "VERBOSE": 2, "DATASET": "paws-x", "TRAINING_METHOD": "monolingual", "LANGS": "en de es fr ja ko zh", "SEED":0, "LEARNING_RATE": "2e-5", "SHUFFLE": 0, "IDS_FILE_NAME": "data/none.pkl"}}
    ScriptTemplateName:
      type: string
      example: div_examples.sh